application: betweetdotnet
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /js
  mime_type: text/javascript
  static_dir: js
- url: /css
  mime_type: text/css
  static_dir: css
- url: /img
  static_dir: img
- url: /.*
  script: main.py


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: latest
