application: betweetdotnet
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /.*
  script: helloworld.py


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: latest
